### ISSUE TITLE
为什么要将老apk和patch文件重组成一虚拟的apk啊

### ISSUE THREAD

**Issue by ftyszyx** [noodle1983/UnityAndroidIl2cppPatchDemo-libboostrap#1]
为什么要将老apk和patch文件重组成一虚拟的apk啊，已经将libil2cpp的加载重定向到新的libil2cpp，任务不是就完成了吗

**Comment by noodle1983** [comment]
asset也要更新，这是我能想到的最简单和直接的方法，你要有其他方案更新asset也行

**Comment by ftyszyx** [comment]
谢谢，你的方法有效

**Comment by sisong** [comment]
我coding中的版本改了一下[方案](https://github.com/sisong/UnityAndroidHotUpdate/tree/dev)：不使用虚拟apk，而是使用完整新版本apk+解包出的个别.so文件；并使用[ApkDiffPatch](https://github.com/sisong/ApkDiffPatch)来生成和应用补丁；      
优点： 这样可以少掉很多代码、只hook了4个函数、逻辑流程简单; 不能热更时拉起新版本apk安装过程；   
缺点： 最大占用磁盘空间可能变大
