### ISSUE TITLE
pthread_spin_unlock 的实现不正确

### ISSUE THREAD

**Issue by ganlvtech** [noodle1983/UnityAndroidIl2cppPatchDemo-libboostrap#10]
https://github.com/noodle1983/UnityAndroidIl2cppPatchDemo-libboostrap/blob/c792861d989227aa9e6763692ba5800b4e6c6c57/pthread_spin_lock.h#L36-L40

https://stackoverflow.com/questions/12183311/difference-in-mfence-and-asm-volatile-memory

`asm volatile ("" ::: "memory")` 编译之后反编译看没有生成任何指令，它只是告诉编译器不要做指令重排吧

```cpp
static inline int pthread_spin_unlock(pthread_spinlock_t *lock) {
	__sync_sub_and_fetch(lock, 1);
	return 0;
}
```

用 `__sync_synchronize()` 也可以，它会生成一个 ARM 的 __dmb(11) 的操作
不用的话就是啥也不管。

测试代码也做了一定的修改

```cpp
void *thread_proc(void *arg) {
    int thread_id = (int) (intptr_t) arg;
    MY_INFO("thread %d start", thread_id);
    for (int i = 0; i < LOOP_COUNT; i++) {
        PthreadWriteGuard guard(g_test_mutex);
        if (a != b || b != c || c != d) {
            MY_ERROR("pthread unit test failed: thread %d: %d %d %d %d", thread_id, a, b, c, d);
        }
        a++;
        b++;
        c++;
        d++;
    }
    MY_INFO("thread %d stop", thread_id);
    pthread_exit(0);
    return 0;
}
```

可以测出 `asm volatile` 和 `__sync_sub_and_fetch` 的差别

![test_mutex](https://user-images.githubusercontent.com/8651285/156884871-d68ffa3f-e3f8-4398-8a84-e6622989f8d0.png)

我可以提交一个 Pull Request

**Comment by noodle1983** [comment]
有理有据， 没啥意见， 提个pr吧

**Comment by noodle1983** [comment]
@ganlvtech 我想重现一下修改之前的错误测试， 我在虚拟机和P40上都没法重现，问问你的重现环境

**Comment by ganlvtech** [comment]
@noodle1983 MI MAX 3，Unity 2018.4 的 android-r16b ndk，编译之后直接放到 /usr/local/tmp 中运行的。可以尝试使用旧的 lock 实现，跑新的 test 代码，不一定每次都能出现，多试几次可能就会出现 a != b 了。

**Comment by ganlvtech** [comment]
@noodle1983 旧的 test 代码没法测出锁的问题，不清楚为什么，可能跟只有一个变量参与原子操作有关。

C++ 20 的原子操作，对于锁的实现应该使用 [Sequentially-consistent ordering](https://en.cppreference.com/w/cpp/atomic/memory_order#Sequentially-consistent_ordering) Memory Order，本条指令不允许被重排，并且该指令之前的所有内存操作必须被同步，不仅仅是当前 atomic 操作的内存。
