### ISSUE TITLE
用这个新版本以后 无限重启 

### ISSUE THREAD

**Issue by BossaNovaCC** [noodle1983/UnityAndroidIl2cppPatchDemo-libboostrap#3]
![image](https://user-images.githubusercontent.com/11451728/62436152-56fb2d80-b771-11e9-99f5-ad643ffe31e3.png)
这个路径会报错找不到 之前版本可以

**Comment by BossaNovaCC** [comment]
用的是25号的版本

**Comment by BossaNovaCC** [comment]
刚才问了一个老哥 解决了 这里是缺少了java的声明 传路径进去这一步 大神麻烦补一下文档

**Comment by noodle1983** [comment]
嗯， 才看到， java init接口改了， set data path参数也改了， 最近有有个Android项目上线在验证

**Comment by noodle1983** [comment]
Unity工程提了， 加了统计Android机型， 加了Unity广告（嘿嘿，用不了）
